### ISSUE TITLE
Can this GitHub repo be archived?

### ISSUE THREAD

**Issue by HenrikBengtsson** [ucsf-wynton/tutorials#12]
@AlexanderPico @dataMaster-Kris @murashka-ucsf 
@reubenthomas @scootermorris , there has been no traffic or updates to this repo since November 2020.  Can we archive this repo on GitHub?

**Comment by AlexanderPico** [comment]
Coincidentally, we're preparing a new "Working on Wynton" workshop for next month. Let's leave this as-is for now so we have access to all available content prepared so far, and then we'll make a plan to consolidate, update, replace, etc.

Sound good?

**Comment by AlexanderPico** [comment]
By the way, other than the official web site (Getting Started, How To), are there other training materials you are aware of?

**Comment by HenrikBengtsson** [comment]
> Sound good?

Good enough reason as any.

> By the way, other than the official web site (Getting Started, How To), are there other training materials you are aware of?

None, AFAIK.

FWIW, I'm trying to set up a Wynton blog, which can be used to share tips'n'trick, how-tos, etc. that does _not_ qualify for the website or does not meet the long-term standard for it.  Contrary to the website, content in a blog post is allowed to expire.  This means we can be more lax about posting info in a blog post.  We can also invite users to post on the blog.

**Comment by AlexanderPico** [comment]
I have unpublished the Pages web site associated with this repo, but I don't appear to have permission to archive the repo. @murashka-ucsf I'm guessing that you do. Can you do this at your convenience?

**Comment by HenrikBengtsson** [comment]
> I have unpublished the Pages web site associated with this repo, but I don't appear to have permission to archive the repo. @murashka-ucsf I'm guessing that you do. Can you do this at your convenience?

Thanks. I'll go ahead and archive this repository now.  After that, it will not be possible to comment here anymore.  If someone has further comments, please reach out on the [Wynton Slack](https://wynton.ucsf.edu/hpc/support/index.html) or email Wynton support.
